name: MLOps Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install DVC
      run: pip install dvc[s3]

    - name: Skip DVC pull
      run: echo "Skipping DVC pull"

    - name: Train model
      run: python src/train.py v2 rf full